PROGRAM ATTENDANCE_MARKS
IMPLICIT NONE
INTEGER :: SID
REAL:: CREDIT, MARKS, ATTMARKS, RATIO, PRCNTGE, DAYS, TDAYS
CHARACTER(100) :: NAME
CREDIT = 1.5 !CREDIT IS 1.5
PRINT*,"ENTER STUDENT ID: "
READ*, SID !TAKING INPUT STUDENT ID
WRITE(*,'("ENTER NAME: ",\)')
READ(*,'(A)') NAME !TAKING INPUT NAME
PRINT*, "NUMBER OF DAYS STUDENT PRESENT : "
READ*, DAYS
PRINT*, "TOTAL NUMBER OF DAYS CLASS HELD: "
READ*, TDAYS
RATIO = DAYS/TDAYS
PRCNTGE = RATIO*100 !ATTENDANCE PERCENTAGE
PRINT*, "ATTENDANCE IS :"
PRINT "(F6.2)" , PRCNTGE
!IF-ELSE STATEMENT / CONTROL STRUCTURE
IF(PRCNTGE >= 90) THEN 
  ATTMARKS = 10
ELSE IF(PRCNTGE >=85 .AND. PRCNTGE < 90) THEN
  ATTMARKS = 9
ELSE IF(PRCNTGE >=80 .AND. PRCNTGE < 85) THEN
  ATTMARKS = 8
ELSE IF(PRCNTGE >=75 .AND. PRCNTGE < 80) THEN
  ATTMARKS = 7
ELSE IF(PRCNTGE >=70 .AND. PRCNTGE < 75) THEN
  ATTMARKS = 6
ELSE IF(PRCNTGE >=65 .AND. PRCNTGE < 70) THEN
  ATTMARKS = 5
ELSE IF(PRCNTGE >=60 .AND. PRCNTGE < 65) THEN
  ATTMARKS = 4
ELSE 
  ATTMARKS = 0
END IF
MARKS = CREDIT * ATTMARKS !TOTAL MARKS CALCULATION
PRINT*, ''
PRINT*,"ALL OUTPUTS :" !ALL OUTPUTS RESPECTIVELY
PRINT*,"STUDENT ID:",SID
PRINT*,"STUDENT NAME :", NAME
PRINT*,"COURSE CREDIT :"
PRINT "(F6.2)", CREDIT
PRINT*,"MARKS :"
PRINT "(F6.2)", MARKS
END PROGRAM ATTENDANCE_MARKS


